pipeline:
  name: pipeline remote
  identifier: pipeline_remote
  tags: {}
  template:
    templateRef: account.acc_temp_remote
    gitBranch: master
    templateInputs:
      stages:
        - stage:
            identifier: s1
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
  projectIdentifier: V
  orgIdentifier: default
