pipeline:
  name: remote123
  identifier: remote123
  projectIdentifier: V
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: ENV
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infr2
          execution:
            steps:
              - step:
                  name: t
                  identifier: t
                  template:
                    templateRef: account.stept123
                    versionLabel: v1
                    gitBranch: main
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
              - step:
                  name: t2
                  identifier: t2
                  template:
                    templateRef: account.steptemp
                    versionLabel: v1
                    gitBranch: master
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        tags: {}
